# Multivariate Linear Regression: Hiring Salary
This notebook predicts *salary ($)* from three features: *experience*, *test score (out of 10)* and *interview score*, using multivariate linear regression (`y = m1*x1 + m2*x2 + m3*x3 + b`).

**Note:** Upload `hiring.csv` to Colab's Files section (`/content/`) before running.

## 1. Import libraries

In [1]:
# Handle data as tables (DataFrames)
import pandas as pd
# Numerical operations (not used directly in this notebook, but common in ML)
import numpy as np
# Linear regression model from scikit-learn
from sklearn import linear_model

## 2. Install and import word2number
Some values in the `experience` column are written as words (e.g. "five"). `word2number` converts them into numbers.

In [2]:
# Install the third-party package from PyPI (needed only once per Colab session)
# Security tip: for reproducible and safer installs, pin the version, e.g. !pip install word2number==1.1
!pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: word2number
  Building wheel for word2number (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5657 sha256=0e15c83747c8b55538f22ee2bcaad9e4c2d27904b0746192b52df9aaf2b4a023
  Stored in directory: /root/.cache/pip/wheels/aa/2b/71/ede4a3c3520a8374778c16c345e0e78e25d1ffe38f4c5c1e8a
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

In [3]:
# Converts number words like "five" into the number 5
from word2number import w2n

## 3. Load the data

In [4]:
# Read the CSV file into a DataFrame
# (the file must be in Colab's /content/ folder, otherwise FileNotFoundError is raised)
df = pd.read_csv('hiring.csv')
# Colab automatically displays the last expression in a cell
df

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

Data Preprocessing

In [5]:
# Convert word values in 'experience' (e.g. "five") to numbers.
# If the value is already a number or NaN (not a string), keep it as it is.
df['experience'] = df['experience'].apply(
    lambda x: w2n.word_to_num(x) if isinstance(x, str) else x
)

In [6]:
# Check the median of 'experience' (used below to fill missing values)
df.experience.median()

6.0

In [7]:
# Fill missing 'experience' values with the median
median_experience = df['experience'].median()
df['experience'] = df['experience'].fillna(median_experience)

In [8]:
# Fill missing test scores with the median test score
median_test_score = df['test_score(out of 10)'].median()

df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(
    median_test_score
)

In [9]:
# Check the cleaned data (no missing values should remain)
df

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

## 4. Train the model

In [10]:
# Create linear regression object
reg = linear_model.LinearRegression()

# Train the model:
# X (features) = all columns except 'salary($)'
# y (target)   = 'salary($)'
reg.fit(df.drop('salary($)',axis='columns'),df['salary($)'])

LinearRegression()

## 5. Make predictions

2 yr experience, 9 test score, 6 interview score

In [11]:
# Original line: reg.predict([[2, 9, 6]])
# The model was trained on a DataFrame with named columns, so passing the input
# with the same column names avoids sklearn's "feature names" warning.
# The logic and the result are exactly the same.
reg.predict(pd.DataFrame([[2, 9, 6]], columns=df.drop('salary($)',axis='columns').columns))

array([47056.91056911])

12 yr experience, 10 test score, 10 interview score

In [12]:
# Original line: reg.predict([[12, 10, 10]])
# Same fix as above: use the same column names as the training data.
reg.predict(pd.DataFrame([[12, 10, 10]], columns=df.drop('salary($)',axis='columns').columns))

array([88227.64227642])