# Train Test Split: Car Prices
This notebook shows how to split data into a training set and a test set with `train_test_split`, train a linear regression model on the training part, and predict on the unseen test part.

**Note:** Upload `carprices (1).csv` to Colab's Files section (`/content/`) before running.

## 1. Import libraries and load the data

In [1]:
# Handle data as tables (DataFrames)
import pandas as pd

In [2]:
# Read the CSV file into a DataFrame
# (the file must be in Colab's /content/ folder, otherwise FileNotFoundError is raised)
df = pd.read_csv("carprices (1).csv")
# Show the first 5 rows to check the data
df.head()

   Mileage  Age(yrs)  Sell Price($)
0    69000         6          18000
1    35000         3          34000
2    57000         5          26100
3    22500         2          40000
4    46000         4          31500

## 2. Separate features (X) and target (y)

In [3]:
# X (input features): the columns used to make the prediction
X = df[['Mileage','Age(yrs)']]

In [4]:
# y (target/label): the value we want to predict, the selling price
y = df['Sell Price($)']

## 3. Split into training and test sets

In [5]:
# Split the data: 80% for training, 20% for testing (test_size=0.2)
# The split is random, so rows (and results) change on every run
# because no random_state is set.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [6]:
# Features used to train the model
X_train

    Mileage  Age(yrs)
16    28000         2
0     69000         6
4     46000         4
13    58780         4
14    82450         7
17    69000         5
1     35000         3
8     91000         8
11    79000         7
9     67000         6
2     57000         5
19    52000         5
6     52000         5
18    87600         8
3     22500         2
15    25400         3

In [7]:
# Features kept aside to test the model (not used in training)
X_test

    Mileage  Age(yrs)
12    59000         5
10    83000         7
7     72000         6
5     59000         5

In [8]:
# Prices (labels) that go with X_train
y_train

16    35500
0     18000
4     31500
13    27500
14    19400
17    19700
1     34000
8     12000
11    19500
9     22000
2     26100
19    28200
6     32000
18    12800
3     40000
15    35000
Name: Sell Price($), dtype: int64

In [9]:
# Prices (labels) that go with X_test (the real answers to compare predictions against)
y_test

12    26000
10    18700
7     19300
5     26750
Name: Sell Price($), dtype: int64

## 4. Train the model and predict

In [10]:
# Linear regression model from scikit-learn
from sklearn.linear_model import LinearRegression
# Create the model object
clf = LinearRegression()
# Train the model using ONLY the training data
clf.fit(X_train, y_train)

LinearRegression()

In [11]:
# Predict prices for the test set; compare with y_test to see how well the model does
clf.predict(X_test)

array([25341.67189582, 16406.54918609, 20526.86089269, 25341.67189582])

## 5. Reproducible split
Setting `random_state` makes the split the same every time you run the code.

In [12]:
# New split: 70% training, 30% testing
# random_state=10 fixes the shuffle, so you always get the same rows in each set.
# Note: this overwrites X_train, X_test, y_train and y_test from the earlier split,
# but the model 'clf' above was already trained on the old split and is not retrained here.
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=10)
X_test

    Mileage  Age(yrs)
7     72000         6
10    83000         7
5     59000         5
6     52000         5
3     22500         2
18    87600         8